"""
Gemini AI Deal Analyzer Module
=============================
Appraises Vinted secondhand listings using Google Gemini 2.5 Flash with
structured output schemas (Pydantic), evaluating market value, deal scores,
condition notes, and resale margins.
"""

import json
import logging
import os
import time
from typing import List, Literal, Optional
from pydantic import BaseModel, Field

from scraper import VintedItem

logger = logging.getLogger("vinted_hunter.analyzer")


class DealAnalysis(BaseModel):
    """Structured valuation generated by Gemini for a single listing."""

    estimated_market_value: float = Field(
        ...,
        description="Estimated fair market value in the same currency, based on brand, model, rarity, and condition.",
    )
    deal_score: int = Field(
        ...,
        ge=1,
        le=10,
        description="Deal rating from 1 (severely overpriced) to 10 (screaming bargain / massive steal).",
    )
    condition_notes: str = Field(
        ...,
        description="Notes highlighting any hidden defects, wear-and-tear, repairs, stains, or red flags noted in the description.",
    )
    resale_profit_margin: float = Field(
        ...,
        description="Estimated profit in nominal currency (market value minus listing price minus ~12% platform/shipping fees).",
    )
    verdict: Literal["MUST BUY", "GOOD DEAL", "FAIR PRICE", "OVERPRICED"] = Field(
        ...,
        description="Clear categorical verdict: MUST BUY (score 9-10), GOOD DEAL (score 7-8), FAIR PRICE (score 5-6), or OVERPRICED (score 1-4).",
    )
    reasoning: str = Field(
        ...,
        description="A concise 1-2 sentence appraisal rationale explaining the score and market context.",
    )


class AnalyzedItem(BaseModel):
    """Complete product listing paired with its Gemini appraisal."""

    item: VintedItem
    analysis: DealAnalysis


class GeminiDealAnalyzer:
    """
    Appraiser service leveraging Google Gemini 2.5 Flash to evaluate listings.
    Uses structured Pydantic response schemas and the official google-genai SDK.
    """

    DEFAULT_MODEL = "gemini-2.5-flash"

    SYSTEM_INSTRUCTION = (
        "You are an expert vintage and secondhand fashion appraiser, reseller, and deal hunter. "
        "Your task is to analyze Vinted secondhand clothing and footwear listings, accurately estimate "
        "their true secondary market resale value (e.g., on eBay, Grailed, Depop, or Vinted), "
        "and calculate whether the listed price represents an extraordinary bargain. "
        "Analyze the brand equity, item desirability, materials, vintage provenance, size desirability, "
        "and scrutinize the description for subtle flaws, stains, fraying, missing accessories, or wear. "
        "Calculate estimated resale profit margin conservatively (assume standard ~12% fees and postage). "
        "Be rigorous, realistic, and objective: do not inflate scores for generic or low-demand fast fashion."
    )

    def __init__(self, api_key: Optional[str] = None, model: str = DEFAULT_MODEL):
        """
        Initialize Gemini Client.

        :param api_key: Google Gemini API Key. If None, loaded from GEMINI_API_KEY env var.
        :param model: Gemini model identifier (defaults to gemini-2.5-flash).
        """
        self.api_key = api_key or os.getenv("GEMINI_API_KEY")
        self.model = model
        self.client = None

        if self.api_key:
            try:
                from google import genai
                self.client = genai.Client(api_key=self.api_key)
                logger.info(f"Gemini client initialized with model '{self.model}'.")
            except ImportError:
                logger.error("google-genai package not found. Run: pip install google-genai")
        else:
            logger.warning("No GEMINI_API_KEY provided. Analyzer will operate in mock evaluation mode.")

    def analyze_item(self, item: VintedItem) -> DealAnalysis:
        """
        Submit a single Vinted item to Gemini 2.5 Flash for structured appraisal.

        :param item: VintedItem instance
        :return: DealAnalysis Pydantic model
        """
        if not self.client:
            return self._mock_appraisal(item)

        from google.genai import types

        prompt = f"""
Appraise the following Vinted listing:
- Title: {item.title}
- Listed Price: {item.price:.2f} {item.currency}
- Brand: {item.brand}
- Size: {item.size}
- Condition stated by seller: {item.condition}
- Seller Description:
\"\"\"{item.description}\"\"\"

Perform a professional appraisal:
1. Estimate true fair secondary market value in {item.currency}.
2. Rate the deal score (1-10):
   - 9-10: Huge steal (listed significantly below market, highly liquid item).
   - 7-8: Good deal (profitable or substantial personal savings).
   - 5-6: Fair price (standard used price, minimal resale upside).
   - 1-4: Overpriced or low-demand fast fashion.
3. Identify condition notes (mention any wear, fading, repairs, or 'None noted - clean condition').
4. Calculate net resale profit margin in {item.currency} (Market Value - Listed Price - estimated 12% seller fees).
5. Choose appropriate verdict: MUST BUY, GOOD DEAL, FAIR PRICE, or OVERPRICED.
6. Provide a concise 1-2 sentence reasoning.
"""

        for attempt in range(1, 4):
            try:
                response = self.client.models.generate_content(
                    model=self.model,
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        system_instruction=self.SYSTEM_INSTRUCTION,
                        response_mime_type="application/json",
                        response_schema=DealAnalysis,
                        temperature=0.2,
                    ),
                )

                # Use parsed output from official SDK or parse JSON text
                if hasattr(response, "parsed") and response.parsed:
                    if isinstance(response.parsed, DealAnalysis):
                        return response.parsed
                    elif isinstance(response.parsed, dict):
                        return DealAnalysis(**response.parsed)

                # Fallback to text parsing
                raw_json = response.text.strip()
                return DealAnalysis.model_validate_json(raw_json)

            except Exception as e:
                logger.warning(f"Gemini API attempt {attempt} failed for item '{item.id}': {e}")
                if "429" in str(e) or "ResourceExhausted" in str(e):
                    backoff = 3 * attempt
                    logger.info(f"Rate limited by Gemini. Sleeping for {backoff}s...")
                    time.sleep(backoff)
                elif attempt == 3:
                    logger.error(f"Failed to appraise item {item.id} after 3 attempts. Falling back to heuristic appraisal.")
                    return self._mock_appraisal(item)

        return self._mock_appraisal(item)

    def analyze_batch(
        self,
        items: List[VintedItem],
        delay_between_requests: float = 0.8,
    ) -> List[AnalyzedItem]:
        """
        Process a list of items sequentially with polite delays to respect rate limits.

        :param items: List of VintedItem instances
        :param delay_between_requests: Throttle time in seconds between API calls
        :return: List of AnalyzedItem pairs
        """
        analyzed_items: List[AnalyzedItem] = []
        total = len(items)

        logger.info(f"Starting Gemini AI appraisal for {total} items...")

        for index, item in enumerate(items, start=1):
            logger.info(f"[{index}/{total}] Appraising '{item.title[:45]}...' ({item.price} {item.currency})")
            analysis = self.analyze_item(item)
            analyzed_items.append(AnalyzedItem(item=item, analysis=analysis))

            if index < total and self.client:
                time.sleep(delay_between_requests)

        return analyzed_items

    def _mock_appraisal(self, item: VintedItem) -> DealAnalysis:
        """
        Intelligent offline heuristic appraiser used when running without an API key
        or during unit tests.
        """
        brand_lower = item.brand.lower()
        title_lower = item.title.lower()
        price = item.price

        # High-value brands multiplier heuristics
        premium_brands = {
            "carhartt": 1.9,
            "barbour": 2.2,
            "arc'teryx": 2.1,
            "levi's": 1.8,
            "stussy": 2.3,
            "patagonia": 1.7,
            "salomon": 1.8,
            "ralph lauren": 1.9,
            "stone island": 2.4,
            "nike": 1.2,
        }

        multiplier = 1.0
        for b, mult in premium_brands.items():
            if b in brand_lower or b in title_lower:
                multiplier = mult
                break

        # Fast fashion penalty
        if any(ff in brand_lower for ff in ["shein", "primark", "boohoo", "george"]):
            multiplier = 0.6

        est_market = round(max(price * multiplier, price * 0.8), 2)
        profit = round((est_market - price) - (est_market * 0.12), 2)

        ratio = est_market / max(price, 1.0)
        if ratio >= 2.0 and profit >= 20:
            score = 9
            verdict = "MUST BUY"
            reason = f"Substantially underpriced for authentic {item.brand}. High resale liquidity with great margin."
        elif ratio >= 1.4 and profit >= 10:
            score = 8
            verdict = "GOOD DEAL"
            reason = f"Priced well below average resale comps for this {item.brand} piece."
        elif ratio >= 1.0:
            score = 6
            verdict = "FAIR PRICE"
            reason = "Market-appropriate valuation for current condition with low resale spread."
        else:
            score = 3
            verdict = "OVERPRICED"
            reason = "Listing price exceeds secondary market value for this brand and tier."

        condition_notes = "Normal pre-owned wear noted. Check seller photos for minor fabric signs."
        if "rip" in item.description.lower() or "hole" in item.description.lower() or "stain" in item.description.lower():
            condition_notes = "Seller notes flaws or marks in description; inspect closely."
            score = max(1, score - 2)

        return DealAnalysis(
            estimated_market_value=est_market,
            deal_score=score,
            condition_notes=condition_notes,
            resale_profit_margin=profit,
            verdict=verdict,
            reasoning=reason,
        )
